/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exer1;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriella Cristini Galvão
 */
public class FrameExer1 extends javax.swing.JFrame {

    /**
     * Creates new form FrameExer1
     */
    public FrameExer1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloCalcular = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        lbPeso = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        tfSexo = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();
        lbCalcular = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTituloCalcular.setText("Calcular IMC");

        tfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoActionPerformed(evt);
            }
        });

        lbPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbPeso.setText("Peso:");

        lbAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAltura.setText("Altura:");

        tfAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlturaActionPerformed(evt);
            }
        });

        lbSexo.setText("Sexo:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCalcular)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAltura)
                            .addComponent(lbSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(tfSexo))
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lbTituloCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTituloCalcular)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeso)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAltura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSexo)
                    .addComponent(tfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCalcular)
                .addGap(18, 18, 18)
                .addComponent(lbCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoActionPerformed

    private void tfAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlturaActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        try{
            double peso = Double.parseDouble(tfPeso.getText());
            double altura = Double.parseDouble(tfAltura.getText());
            String sexo = tfSexo.getText();
            double imc = peso/(altura*altura);

            if(sexo.equalsIgnoreCase("F")||sexo.equalsIgnoreCase("Feminino")){
                if(imc<19.1){
                   String resCond = String.format("Abaixo do peso.");
                    lbCalcular.setText(resCond);
                }
                if(imc==19.1||imc<25.8){
                   String resCond = String.format("Peso normal");
                    lbCalcular.setText(resCond);
                }
                if(imc==25.8||imc<27.3){
                   String resCond = String.format("Marginalmente acima do  peso");
                    lbCalcular.setText(resCond);
                }
                if(imc==27.3||imc<32.3){
                   String resCond = String.format("Acima do peso ideal");
                    lbCalcular.setText(resCond);
                }
                if(imc>32.3){
                   String resCond = String.format("Obeso");
                    lbCalcular.setText(resCond);
                }
            }else if(sexo.equalsIgnoreCase("M")||sexo.equalsIgnoreCase("Masculino")){
                if(imc<20.7){
                   String resCond = String.format("Abaixo do peso");
                    lbCalcular.setText(resCond);
                }
                if(imc==20.7||imc<26.4){
                   String resCond = String.format("Peso normal");
                    lbCalcular.setText(resCond);
                }
                if(imc==26.4||imc<27.8){
                   String resCond = String.format("Marginalmente acima do  peso");
                    lbCalcular.setText(resCond);
                }
                if(imc==27.8||imc<31.1){
                   String resCond = String.format("Acima do peso ideal");
                    lbCalcular.setText(resCond);
                }
                if(imc>31.1){
                   String resCond = String.format("Obeso");
                    lbCalcular.setText(resCond);
                } 
            }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, insira valores válidos para peso e altura.", "Erro", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btCalcularActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbCalcular;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTituloCalcular;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfPeso;
    private javax.swing.JTextField tfSexo;
    // End of variables declaration//GEN-END:variables
}
