/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exercicio2;

/**
 *
 * @author aluno
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbRendaBruta = new javax.swing.JLabel();
        tfRendaBrutaMensal = new javax.swing.JTextField();
        lbDependentes = new javax.swing.JLabel();
        tfDependentes = new javax.swing.JTextField();
        lbTotalDeducoes = new javax.swing.JLabel();
        lbTD = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        tfDeducoesTotal = new javax.swing.JTextField();
        lbRendaBrutaAnual = new javax.swing.JLabel();
        lbBaseCalculo = new javax.swing.JLabel();
        lbImpostoDevido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitulo.setText("Calculo IR");

        lbRendaBruta.setText("Renda Bruta Mensal");
        lbRendaBruta.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lbRendaBrutaComponentAdded(evt);
            }
        });

        tfRendaBrutaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRendaBrutaMensalActionPerformed(evt);
            }
        });

        lbDependentes.setText("Dependentes");

        tfDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDependentesActionPerformed(evt);
            }
        });

        lbTotalDeducoes.setText("Total Deduções ");

        lbTD.setText("(saúde,educação,etc)");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        tfDeducoesTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDeducoesTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbImpostoDevido, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(lbTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfRendaBrutaMensal, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(lbRendaBruta)
                                            .addComponent(lbDependentes)
                                            .addComponent(tfDependentes))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbTotalDeducoes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbTD))
                                        .addComponent(tfDeducoesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbBaseCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10))
                                .addComponent(lbRendaBrutaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btCalcular)
                                    .addGap(114, 114, 114))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRendaBruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRendaBrutaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbDependentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalDeducoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDeducoesTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btCalcular)
                .addGap(18, 18, 18)
                .addComponent(lbRendaBrutaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBaseCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbImpostoDevido, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbRendaBrutaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lbRendaBrutaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbRendaBrutaComponentAdded

    private void tfRendaBrutaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRendaBrutaMensalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRendaBrutaMensalActionPerformed

    private void tfDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDependentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDependentesActionPerformed

    private void tfDeducoesTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDeducoesTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDeducoesTotalActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCalcularActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JLabel lbBaseCalculo;
    private javax.swing.JLabel lbDependentes;
    private javax.swing.JLabel lbImpostoDevido;
    private javax.swing.JLabel lbRendaBruta;
    private javax.swing.JLabel lbRendaBrutaAnual;
    private javax.swing.JLabel lbTD;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTotalDeducoes;
    private javax.swing.JTextField tfDeducoesTotal;
    private javax.swing.JTextField tfDependentes;
    private javax.swing.JTextField tfRendaBrutaMensal;
    // End of variables declaration//GEN-END:variables
}
